# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategoria',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('bodyszort', froala_editor.fields.FroalaField()),
                ('body', froala_editor.fields.FroalaField()),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='admina')),
            ],
        ),
    ]
