# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161123_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images'),
        ),
    ]
